# Generated by Django 5.2.7 on 2025-11-20 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_entrega', models.FileField(upload_to='entregas/')),
                ('comentarios_estudiante', models.TextField(blank=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('estado_entrega', models.CharField(choices=[('entregado', 'Entregado'), ('revisado', 'Revisado'), ('atrasado', 'Atrasado')], default='entregado', max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='tareas.tarea')),
            ],
        ),
    ]
