# Generated by Django 5.2.8 on 2025-11-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_apellido_alter_customuser_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('usuarios_crear_usuario', 'Puede crear usuarios'), ('usuarios_editar_usuario', 'Puede editar usuarios'), ('roles_editar_rol', 'Puede editar roles y permisos')]},
        ),
    ]
