# Generated by Django 5.2.8 on 2025-11-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('registrar_usuario', 'Puede registrar usuarios'), ('enviar_codigo_recuperacion', 'Puede enviar códigos de recuperación'), ('validar_codigo_recuperacion', 'Puede validar códigos de recuperación'), ('restablecer_password', 'Puede restablecer contraseñas'), ('cambiar_password', 'Puede cambiar la contraseña'), ('ver_roles', 'Puede ver roles del sistema'), ('asignar_roles', 'Puede asignar roles'), ('crear_roles', 'Puede crear nuevos roles'), ('ver_permisos', 'Puede ver permisos'), ('asignar_permisos', 'Puede asignar permisos'), ('crear_permisos', 'Puede crear nuevos permisos'), ('enviar_recordatorios', 'Puede enviar recordatorios de tareas')]},
        ),
    ]
