# Generated by Django 5.2.8 on 2025-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
