# Generated by Django 5.2.7 on 2025-11-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('peso_porcentual', models.PositiveIntegerField()),
                ('tipo_tarea', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen')], max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='asignaturas.asignatura')),
            ],
        ),
    ]
