# Generated by Django 5.2.7 on 2025-11-20 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0002_asignatura_docente'),
        ('entrega_tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('retroalimentacion_docente', models.TextField(blank=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('estado_calificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('publicado', 'Publicado')], default='pendiente', max_length=10)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='entrega_tareas.entregatarea')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFinalAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_finales', to='asignaturas.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_finales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura')},
            },
        ),
    ]
