# Generated by Django 5.2.8 on 2025-11-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacionentrega',
            options={'permissions': [('calificar_tareas', 'Puede calificar tareas'), ('ver_calificaciones', 'Puede ver calificaciones')]},
        ),
    ]
